# Inserts a blank line between shell prompts
add_newline = true
# Prompt format.
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$rust\
$python\
$shell\
$character
"""

[directory]
truncate_to_repo = false

[character]
format = "\n$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
